version: 2.1

orbs:
  jest: blimmer/jest@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  integration-test-docker-executor:
    docker:
      - image: circleci/node:fermium
    working_directory: ~/project/test-project
    steps:
      - checkout:
          path: ~/project
      - run: npm ci
      - run: jest/restore-cache
      - run: npm run test
      - run: touch .jest-cache/RESTORED_FILE.txt
      - run: jest/save-cache
  integration-test-remote-docker:
    docker:
      - image: circleci/node:fermium
    working_directory: ~/project/test-project
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          docker_layer_caching: false
      - run: jest/restore-cache
      - run: docker-compose build test
      - run: docker-compose up -d test
      - run: docker-compose exec test './node_modules/.bin/jest'
      - run: touch .jest-cache/RESTORED_FILE.txt
      - run: jest/save-cache
  integration-test-machine-executor:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/project/test-project
    steps:
      - checkout:
          path: ~/project
      - run: npm ci
      - run: jest/restore-cache
      - run: npm run test
      - run: touch .jest-cache/RESTORED_FILE.txt
      - run: jest/save-cache

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb sourc
  test:
    jobs:
      - integration-test-docker-executor
      - integration-test-remote-docker
      - integration-test-machine-executor
