description: >
  This command writes out jest orb dependencies
steps:
  - run:
      name: Export commit hashes for cache keys
      command: |
       git rev-parse HEAD~1 > /tmp/jest-cache-previous-commit-hash.txt
       git rev-parse HEAD > /tmp/jest-cache-current-commit-hash.txt
